### ISSUE TITLE
Nothing is shown by the plugin, except for agents details

### ISSUE THREAD

**Issue by gabienache** [gocd/gocd-analytics-plugin#161]
Hi. I've installed Analytics Plugin 3.0.0-5 on a GoCD 20.8. I've enabled logs.
Nothing is shown on the pipelines if clicked on analytics button
<img width="664" alt="Screenshot 2020-11-16 at 14 29 28" src="https://user-images.githubusercontent.com/12858163/99267487-aeb98d00-282c-11eb-8047-0716c9cc0631.png">
<img width="1038" alt="Screenshot 2020-11-16 at 14 26 23" src="https://user-images.githubusercontent.com/12858163/99267490-afeaba00-282c-11eb-8d70-1773f4883e28.png">

Is there some configuration I've missed?
Thank you.

**Comment by maheshp** [comment]
@gabienache have you placed the HighChart JS files as required. Can you please check the (plugin prerequisites)[https://github.com/gocd/gocd-analytics-plugin/blob/main/docs/Install.md#prerequisites]

**Comment by gabienache** [comment]
@maheshp Thank you. You were right. I missed that part.
