### ISSUE TITLE
Does this plugin measure time from commit pushed until job scheduled?

### ISSUE THREAD

**Issue by MPV** [gocd/gocd-analytics-plugin#289]
We'd like to measure this time, as (if you're not using webhooks) this can be a somewhat large part of the time developers spend waiting for their code to be tested.

**Comment by arvindsv** [comment]
I don't think it does. It works on the basis of stage notification events. It's a good idea, but it would need deeper integration with the material subsystem to know when it saw the commits and then tying it to the pipelines it triggered.

**Comment by MPV** [comment]
Is the first data point measured from the scheduling of a job? 
Or from the date of when a material change/commit has been done originally?
