### ISSUE TITLE
JS files not found when placed in location cited in docs

### ISSUE THREAD

**Issue by christopappas** [gocd/gocd-analytics-plugin#367]
Hey there,

I'm running GoCD 20.10.0 via helm chart/kubernetes. I am hoping to use this plugin; however, the application cannot seem to find the JS files when they are placed where the docs say: `/go-server/analytics-assets`. What's curious is that that folder does not even exist at that location:

```
bash-5.0$ pwd
/
bash-5.0$ ls
bin                   etc                   godata                media                 root                  sys
dev                   go-server             home                  mnt                   run                   tmp
docker-entrypoint.d   go-working-dir        lib                   opt                   sbin                  usr
docker-entrypoint.sh  gocd-jre              lib64                 proc                  srv                   var
bash-5.0$ ls go-server
LICENSE         bin             config          lib             logs            run             wrapper         wrapper-config
```

Looking at the error in my browser, I have determined that the app wants the files to live here: `/go-working-dir/work/jetty-0_0_0_0-8153-cruise_war-_go-any-/webapp/WEB-INF/rails/public/assets/plugins/com.thoughtworks.gocd.analytics/c7f5519fa996a9b94b06052e14f6d180456cddef95609db11755f64ef28f685a`, and if I manually drop the files there, I can get graphs to render.

I'm in a particular bind because because my setup is intended to be stateless/IaC kubernetes, I need this file's existence to persist pod restarts. I thought I'd be clever and mount that super long path above and mount the single JS files; however, the GoCD application wants to delete that directory on startup (when the pod rolls).

Anyway, before I go any deeper into a hacky k8s solution I wanted to ask: can you confirm that this file path, `/go-server/analytics-assets`, IS the correct place for the highchart JS files to live? and then, if it is, any thoughts as to what might be going wrong?

Thanks for your time,
Chris

**Comment by arvindsv** [comment]
Looking at [the documentation](https://github.com/gocd/gocd-analytics-plugin/blob/main/docs/Install.md) and the tree shown there, it looks like that's the right place. Did you mount it there? Did it not work?

It's not surprising that the (empty) directory is not present. This is a requirement of the plugin and not of GoCD. But, the contents of that directory will be made available (either by copying or otherwise) by GoCD. You shouldn't need to put it into its temporary work directory.

**Comment by christopappas** [comment]
Yup, that's correct. I did mount it to `/go-server/analytics-assets` successfully (using an init container) such that, once the gocd-server pod is up and running, I can shell into the pod and see the files in that directory (`/go-server/analytics-assets`); however the JS is not found when I click the Analytics tab in the GoCD UI.

There are 404s when trying to get the assets (looking at the web browser's dev console). The browser seemed to think the files need to live `/go-working-dir/work/jetty-0_0_0_0-8153-cruise_war-_go-any-/webapp/WEB-INF/rails/public/assets/plugins/com.thoughtworks.gocd.analytics/c7f5519fa996a9b94b06052e14f6d180456cddef95609db11755f64ef28f685a`. Perhaps there is some kind of simlinking that's not working? 🤷

**Comment by arvindsv** [comment]
I think this has something to do with the working directory the server is in, when run as a Docker container. The [path is correct](https://github.com/gocd/gocd/search?q=GO_ANALYTICS_PLUGIN_EXTERNAL_ASSETS), but it is set to `./analytics-assets`. Looking at the [entrypoint script](https://github.com/gocd/gocd/search?q=GO_ANALYTICS_PLUGIN_EXTERNAL_ASSETS), there seems to be a `/go-working-dir` which might be the real working directory when inside a Docker container, as so could correspond to the `.` in `./analytics-assets`.

Could you try mounting it at `/go-working-dir/analytics-assets` to see if it works? If not, I'll try and take a look over the weekend.

**Comment by arvindsv** [comment]
By the way, the reason it looks in the temporary work directory is that the assets should be copied over there at runtime (by [this code](https://github.com/gocd/gocd/blob/3e948218bfb163c5c3d2bf5140cb4a12f110769e/server/src/main/java/com/thoughtworks/go/server/service/plugins/AnalyticsPluginAssetsService.java#L129)) to make it easier to serve along with the rest of the assets.

**Comment by christopappas** [comment]
```
Could you try mounting it at /go-working-dir/analytics-assets to see if it works? If not, I'll try and take a look over the weekend.
```
Can do, I'll give this a try and circle back

**Comment by christopappas** [comment]
Mounted the assets in `/go-working-dir/analytics-assets/`, started the server, and no JS errors when looking at the analytics tab! 🎉 

This is great! Thank you so much for the help! Definitely would not have found that bit of code on my own.

**Comment by christopappas** [comment]
Created a PR to update the docs: https://github.com/gocd/gocd-analytics-plugin/pull/369

**Comment by arvindsv** [comment]
Glad it worked. :) Thanks for the PR. It's merged. Closing this issue.
