### ISSUE TITLE
Analytics plugin 2.3.0 and 3.0.0-5 - database connectivity issue

### ISSUE THREAD

**Issue by vf-vnovakovic** [gocd/gocd-analytics-plugin#55]
Hello everyone,

I did the following upgrade path for testing purposes:

I had completed first upgrade of go-server from 2.3.0 to 2.4.0 than I had perform migration database from H2 to PostgreSQL and than afterwards installation of analytics plugin 2.3.0.

This is ending with following problem when I want to connect analytics plugin with PostgreSQL database:

**Save failed. There are errors in the plugin settings. Please fix them and resubmit.

Error connecting to database, reason - Found non-empty schema(s) "public" without metadata table! Use baseline() or set baselineOnMigrate to true to initialize the metadata table.**

Screenshots:
![image](https://user-images.githubusercontent.com/69468390/91656512-8afe6a80-eab9-11ea-8764-1a6f7e1af4a3.png)

![image](https://user-images.githubusercontent.com/69468390/91656626-88504500-eaba-11ea-9f67-6b366236144f.png)

Afterwards, I have moved also to 20.5.0 expecting that I will be able to use Analytics version 3.0.0-5, but ending with same error. 

I would appreciate hints from your side how to troubleshoot further this issue. Where I should _set baselineOnMigrate_ to _true_?

Kind regards,
Vlad

**Comment by arvindsv** [comment]
You're not using the same Postgres schema as the one you used for GoCD, right? Analytics continues to use a different schema. If you had one earlier, you should be able to continue using it.

Is there more information in the plugin logs?

**Comment by vf-vnovakovic** [comment]
Hi ArvindSV,

good to see you here :-)  as first to answer your question:

My PSQL schema under latest migration to 20.5.0 looks like following. 

**gocd=# \dn
  List of schemas
  Name  |  Owner
--------+----------
 public | postgres
(1 row)
gocd=#**

and I'm trying to add analytics >20.3.0 or 3.0.0-5 without previous analytics installations.

Review of previous steps:

I was trying more like vanilla installation on Ubuntu 20.4, starting with go-server 20.3.0 and H2, than upgrading to go-server 20.4.0 and upgrading to PostgreSQL 12. This whole process has been completed successfully. This was an preparation to add Analytics 20.3.0, but I experience errors  that you have seen in my previous post.

Afterwards, the next idea was upgrading to  go-server 20.5.0 and give a try to Analytics 3.0.0-5 - but it end up with same results.

Than I follow up also installation instruction creating separate empty gocd_analytics database as it is described in:

https://github.com/gocd/gocd-analytics-plugin/blob/main/docs/Install.md

and analytics could connect (no errors), the issue is that stats after running test pipelines were empty, no single graphs at all, just an empty page.

As my latest try I have added: **set baselineOnMigrate** to **true** in:

_gocd-analytics-plugin/src/main/java/com/thoughtworks/gocd/analytics/db/PostgresqlDatabase.java_

added line 86
**flyway.setBaselineOnMigrate(true);**

and I have compiled and repack analytics jar file for testing purposes, than when I wanted to connect to migrated 20.5.0 gocd database, I got some other error messages, could be that is a wrong way to fix the problem :-) :

![image](https://user-images.githubusercontent.com/69468390/91662232-5f8f7600-eae1-11ea-9c9b-196e98985697.png)

In a meantime I have found a typo in goCD migration tool document, please let me know how can I contribute and send a merge request for documentation corrections or updates?

Kind regards,
Vlad

**Comment by arvindsv** [comment]
> Than I follow up also installation instruction creating separate empty gocd_analytics database as it is described in:
> https://github.com/gocd/gocd-analytics-plugin/blob/main/docs/Install.md
> and analytics could connect (no errors), the issue is that stats after running test pipelines were empty, no single graphs at all, just an empty page.

That part is expected. The analytics DB information is not retroactive. It doesn't connect to GoCD's DB to find old pipeline run information. It's only for pipeline runs going forward. So, as you run pipelines,  the data should start showing up.

Maybe you were expecting old data to show up, and that's why you thought it wasn't successful?

> added line 86
> flyway.setBaselineOnMigrate(true);
> and I have compiled and repack analytics jar file for testing purposes, than when I wanted to connect to migrated 20.5.0 gocd database, I got some other error messages, could be that is a wrong way to fix the problem :-) :

:) Yeah. You shouldn't need to set properties and recompile, etc. Not sure what `setBaselineOnMigrate` is, but we should ignore it for now, I think.

> In a meantime I have found a typo in goCD migration tool document, please let me know how can I contribute and send a merge request for documentation corrections or updates?

Sure. The codebase of the migrator tool is at: https://github.com/gocd/gocd-database-migrator. Is that where you saw the typo?

**Comment by vf-vnovakovic** [comment]
> > Than I follow up also installation instruction creating separate empty gocd_analytics database as it is described in:
> > https://github.com/gocd/gocd-analytics-plugin/blob/main/docs/Install.md
> > and analytics could connect (no errors), the issue is that stats after running test pipelines were empty, no single graphs at all, just an empty page.
> 
> That part is expected. The analytics DB information is not retroactive. It doesn't connect to GoCD's DB to find old pipeline run information. It's only for pipeline runs going forward. So, as you run pipelines, the data should start showing up.
> 
> Maybe you were expecting old data to show up, and that's why you thought it wasn't successful?

Correct, I was thinking that data has been collected from main goCD database because there are historical data about all executions and the time that each task needed to complete. This was my wrong impression that made all trouble, kind of    TL;DR syndrome 😊
 
> > In a meantime I have found a typo in goCD migration tool document, please let me know how can I contribute and send a merge request for documentation corrections or updates?
> 
> Sure. The codebase of the migrator tool is at: https://github.com/gocd/gocd-database-migrator. Is that where you saw the typo?

This GitHub document is correct but I was referring to the official release documentation: 

https://docs.gocd.org/current/installation/upgrade_to_gocd_20.5.0.html  

How community can contribute for those improvements and corrections?

**Comment by arvindsv** [comment]
> This GitHub document is correct but I was referring to the official release documentation:

> https://docs.gocd.org/current/installation/upgrade_to_gocd_20.5.0.html

> How community can contribute for those improvements and corrections?

Ah, ok. The source of it is here: https://github.com/gocd/docs.go.cd/blob/master/content/installation/upgrade_to_gocd_20.5.0.md

**Comment by vf-vnovakovic** [comment]
>> How community can contribute for those improvements and corrections?

> Ah, ok. The source of it is here: https://github.com/gocd/docs.go.cd/blob/master/content/installation/upgrade_to_gocd_20.5.0.md

thank  you.

I'm still frustrated with "blank Anayltics screen". I can see that even **jobs** table in **gocd_analytics** is populated with latest data. 

![image](https://user-images.githubusercontent.com/69468390/91707766-9b2d4d00-eb80-11ea-9163-1d382f7cfd89.png)

![image](https://user-images.githubusercontent.com/69468390/91707813-b009e080-eb80-11ea-8a93-3ec1d589dd94.png)

![image](https://user-images.githubusercontent.com/69468390/91707881-c44ddd80-eb80-11ea-81d4-0cf05d118a57.png)

**Comment by GaneshSPatil** [comment]
@vf-vnovakovic - do you see any errors at the developer's console which says something "**_Failed to load resource_**" for `highcharts.src.js` or `no-data-to-display.src.js` or `xrange.src.js`??

**Comment by vf-vnovakovic** [comment]
> [updated] - Please open the pipeline analytics on the dashboard, or visit the global analytics page before visiting page's  developer console.

Screenshot of global analytics page:

![image](https://user-images.githubusercontent.com/69468390/91711251-e7c75700-eb85-11ea-8c15-766f14967660.png)

![image](https://user-images.githubusercontent.com/69468390/91711399-1e04d680-eb86-11ea-80a6-6c739b371959.png)

**Comment by GaneshSPatil** [comment]
@vf-vnovakovic - did we install the [`HighCharts` external library](https://github.com/gocd/gocd-analytics-plugin/blob/main/docs/Install.md#highcharts-js) as mentioned in the [Prerequisites of the plugin installation](https://github.com/gocd/gocd-analytics-plugin/blob/main/docs/Install.md#prerequisites)?

**Comment by vf-vnovakovic** [comment]
> @vf-vnovakovic - did we install the [`HighCharts` external library](https://github.com/gocd/gocd-analytics-plugin/blob/main/docs/Install.md#highcharts-js) as mentioned in the [Prerequisites of the plugin installation](https://github.com/gocd/gocd-analytics-plugin/blob/main/docs/Install.md#prerequisites)?

Exactly this was missing. All works now. thank you four your guidance.

 
![image](https://user-images.githubusercontent.com/69468390/91714138-64a8ff80-eb8b-11ea-86bb-f742b37f6de4.png)

**Comment by GaneshSPatil** [comment]
@vf-vnovakovic - glad that it worked :)

I'll close this issue now.

**Comment by vf-vnovakovic** [comment]
All is good with a software, I would like just to highlight where I have initially failed during installation process:

1. I tried to connect goCD to cruise/gocd database insted to create empty database **gocd_analytics**
2. I forgot that installation instruction for 3.0.0-5 beside Analytics jar package needs also installation of:

https://code.highcharts.com/6.1.3/modules/no-data-to-display.src.js
https://code.highcharts.com/6.1.3/modules/xrange.src.js
https://code.highcharts.com/6.1.3/highcharts.src.js 

downloaded at /var/lib/go-server/analytics-assets or C:\Program Files (x86)\Go Server\analytics-assets

Thank you all!
