### ISSUE TITLE
Incorrect Prerequisites

### ISSUE THREAD

**Issue by benjaminclauss** [gocd/gocd-analytics-plugin#583]
https://github.com/gocd/gocd-analytics-plugin/blob/54996c3bd1eca8a96ec62d5406c57885bf8b2a20/docs/Install.md

> - GoCD server version **20.5.0** or higher is needed.

Using GoCD Version: 20.7.0
Plugin Version: 3.1.0-325

<img width="1756" alt="Screen Shot 2022-03-05 at 3 07 34 PM" src="https://user-images.githubusercontent.com/53198018/156899939-8f31822b-f7ca-489b-91d9-d9de5c3700aa.png">

What versions of GoCD and PostgreSQL are supported for each release?

**Comment by chadlwilson** [comment]
You are using an experimental release of the plugin, not a stable/official release. Use a stable release if you want to maximise chances of docs being correct.

AFAIK only Postgres 9.6 is supported.

**Comment by benjaminclauss** [comment]
Sorry about that!
worked with a stable/official release

**Comment by chadlwilson** [comment]
It would be a really good idea to upgrade your GoCD if at all possible. GoCD `20.7.0` has some pretty serious security vulnerabilities. From `20.7.0` -> `21.4.0`, the upgrade should be relatively simple I believe, as don't think there have been major DB-level or configuration changes.
