### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by M-JobPixel** [gocd/gocd-analytics-plugin#613]
I'm trying to build the plugin and aside from a couple of library errors all seemed to be going well until I got to

```
> Task :dropDB FAILED
Attempting to drop DB 'gocd_test' on 'localhost'
```

Does this mean I need postgres installed on localhost to build the plugin?

If not what does it mean?

I don't really want to build the plugin on my GoCD server and even there the postgres db won't be on localhost.

**Comment by chadlwilson** [comment]
Yeah, running integration tests relies on a Postgres being available locally on the default port. You can probably run it as a container if you'd prefer.

**Comment by M-JobPixel** [comment]
Ah, ok thanks. Running it in docker seems like a good compromise, I can do that. Thanks.
