### ISSUE TITLE
Connection error???

### ISSUE THREAD

**Issue by petr-reznicek** [gocd/gocd-analytics-plugin#769]
![image](https://user-images.githubusercontent.com/69631730/196380918-07e80f0d-8f31-4d38-9da7-798f1b447974.png)

**Comment by petr-reznicek** [comment]
It seems that this happened after upgrade to GoCD 22.2.0. PostgressDb is still alive and accessible. Btw. setting of your plugin in GoCD I am not able to save. After click on Save button, the pop up stays open and nothing changes.

**Comment by chadlwilson** [comment]
More information would probably be required to give any suggestions here. Please investigate the server logs and the plugin-specific logs to look for other errors, especially if you just upgraded.

At the very least the full stack trace would be required, as well as some detail about what upgrade you performed (from which version) and the nature of your environment and GoCD deployment. You might want to look at the issue template in gocd at https://github.com/gocd/gocd/issues/new for the detail required.

**Comment by chadlwilson** [comment]
Closing this as there's not enough information here. Will re-open if you're able to provide additional information on your configuration and what you have tried in terms of your DB connection configuration.
